# 01. Знакомство с `torch.Tensor`

V 0.1 04.02.2021

---

При решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использование функционала библиотеки `torch`.

[PyTorch documentation](https://pytorch.org/docs/stable/#pytorch-documentation)

In [2]:
import torch
import numpy 

## 1.1 Создание тензоров и выполнение базовых операций над ними

[Документация по функциям для создания тензоров](https://pytorch.org/docs/stable/torch.html#creation-ops)

[Документация по функциям для работы с индексами](https://pytorch.org/docs/stable/torch.html#indexing-slicing-joining-mutating-ops)

1.1.1 Создайте двумерный тензор размера (8, 8). Используя как можно меньше операций, добейтесь расстановки кодов "шахматных фигур".

Ожидаемый результат:

```
[[-4., -3., -2., -6., -5., -2., -3., -4.],
 [-1., -1., -1., -1., -1., -1., -1., -1.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [1., 1., 1., 1., 1., 1., 1., 1.],
 [4., 3., 2., 6., 5., 2., 3., 4.]]
```

In [3]:
tensor_fst = torch.tensor([[4, 3, 2, 6, 5, 2, 3, 4]])
tensor111 = torch.cat([
    - tensor_fst,
    - torch.ones_like(tensor_fst),
    torch.zeros(4, 8),
    torch.ones_like(tensor_fst),
    tensor_fst
])

tensor111

tensor([[-4., -3., -2., -6., -5., -2., -3., -4.],
        [-1., -1., -1., -1., -1., -1., -1., -1.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 4.,  3.,  2.,  6.,  5.,  2.,  3.,  4.]])

1.1.2 Средствами `torch` рассчитать произведения четных чисел от 2 до 20 на ближайшие к ним бОльшие нечетные числа.

In [4]:
torch.arange(2, 21, 2) * torch.arange(3, 22, 2)

tensor([  6,  20,  42,  72, 110, 156, 210, 272, 342, 420])

1.1.3 Создать тензор размера 11x7 вида: [[1, 2, 3, ..., 7], [11, 12, 13, ..., 17], [21, 22, 23, ..., 27], ..., [101, 102, 103, ..., 107]]

In [5]:
torch.arange(1, 111).reshape(11, 10)[:, :7]

tensor([[  1,   2,   3,   4,   5,   6,   7],
        [ 11,  12,  13,  14,  15,  16,  17],
        [ 21,  22,  23,  24,  25,  26,  27],
        [ 31,  32,  33,  34,  35,  36,  37],
        [ 41,  42,  43,  44,  45,  46,  47],
        [ 51,  52,  53,  54,  55,  56,  57],
        [ 61,  62,  63,  64,  65,  66,  67],
        [ 71,  72,  73,  74,  75,  76,  77],
        [ 81,  82,  83,  84,  85,  86,  87],
        [ 91,  92,  93,  94,  95,  96,  97],
        [101, 102, 103, 104, 105, 106, 107]])

1.1.4 Написать функцию, которая для целых значений `n` и `m` будет возвращать тензор размера `n`x`m`, заполненный текстурой размера 2x2, состоящей из следующих значений:

```
0 1

2 3

```

Пример для n = 4 и m = 5:

```
0 1 0 1 0

2 3 2 3 2

0 1 0 1 0

2 3 2 3 2
```

In [6]:
def make_texture(n: int, m: int) -> torch.LongTensor:
    a = torch.tensor([[0, 1], [2, 3]])
    return torch.tile(a, (n // 2 + n % 2, m // 2 + m % 2))[:n + 1 - n % 2, :m + 1 - m % 2]

make_texture(4, 5)

tensor([[0, 1, 0, 1, 0],
        [2, 3, 2, 3, 2],
        [0, 1, 0, 1, 0],
        [2, 3, 2, 3, 2]])

1.1.5 Сгенерировать двумерный тензор `t` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в дипазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида $ax+b$ так, что после нормализации максимальный элемент масива будет равен 1.0, минимальный 0.0

In [7]:
t = torch.rand(4, 7) * 20
t

tensor([[ 7.8805, 19.0945,  8.3864, 11.1853, 18.6860,  1.5009,  8.4226],
        [12.6934,  1.7397, 12.4383, 14.9440,  1.7548,  8.2349, 18.1694],
        [ 1.3972,  9.6906, 11.9138, 19.5245,  7.9878, 17.3230, 12.6777],
        [16.1896,  0.3399,  0.2018, 16.4878, 13.7981,  7.0061,  4.1680]])

In [8]:
(t - t.min()) / (t.max() - t.min())

tensor([[0.3974, 0.9777, 0.4236, 0.5684, 0.9566, 0.0672, 0.4254],
        [0.6465, 0.0796, 0.6333, 0.7629, 0.0804, 0.4157, 0.9299],
        [0.0619, 0.4911, 0.6061, 1.0000, 0.4029, 0.8861, 0.6457],
        [0.8274, 0.0071, 0.0000, 0.8428, 0.7036, 0.3521, 0.2053]])

[Random Sampling](https://pytorch.org/docs/stable/torch.html#random-sampling)

[Distributions](https://pytorch.org/docs/stable/distributions.html)

1.1.6 Задать два двумерных тензора `ar1` и `ar2` размерности (4, 7), состоящих из случайных целых чисел в пределах от 0 до 10. Построить двумерный тензор размерности (4, 7), каждый элемент которого представляет собой максимум из двух значений, находящихся на аналогичной позиции в тензорах `ar1`, `ar2`.

[Reductions ops](https://pytorch.org/docs/stable/torch.html#reduction-ops)

In [9]:
ar1 = torch.randint(0, 10, (4, 7))
ar2 = torch.randint_like(ar1, 0, 10)

new_arr = torch.stack([ar1, ar2], dim=0)
new_arr.shape

torch.Size([2, 4, 7])

In [10]:
new_arr

tensor([[[1, 2, 8, 6, 0, 6, 6],
         [0, 3, 2, 4, 1, 5, 7],
         [7, 7, 3, 8, 3, 4, 6],
         [0, 3, 2, 1, 0, 4, 1]],

        [[8, 3, 1, 8, 1, 8, 3],
         [2, 0, 6, 7, 7, 2, 7],
         [0, 7, 5, 9, 6, 3, 6],
         [4, 7, 2, 6, 7, 8, 5]]])

In [11]:
new_arr.max(dim=0)[0]

tensor([[8, 3, 8, 8, 1, 8, 6],
        [2, 3, 6, 7, 7, 5, 7],
        [7, 7, 5, 9, 6, 4, 6],
        [4, 7, 2, 6, 7, 8, 5]])

1.1.7 Создать тензор из 20 случайных целых чисел от 0 до 100. Получить второе сверху значение в тензоре. Определить индекс этого значения.

In [12]:
torch.randint(0, 101, (20, )).topk(2)

torch.return_types.topk(
values=tensor([100,  95]),
indices=tensor([17,  0]))

## 1.2 Распространение

[Numpy broadcasting](https://numpy.org/devdocs/user/theory.broadcasting.html)

[Torch broadcasting](https://pytorch.org/docs/stable/notes/broadcasting.html)

1.2.1 Создать тензор 11x7 вида: `[[1, 2, 3, ..., 7], [11, 12, 13, ..., 17], [21, 22, 23, ..., 27], ..., [101, 102, 103, ..., 107]]`. При решении задачи применить технику распространения.

In [13]:
torch.arange(1, 8).reshape(1, -1) + torch.arange(0, 101, 10).reshape(-1, 1)

tensor([[  1,   2,   3,   4,   5,   6,   7],
        [ 11,  12,  13,  14,  15,  16,  17],
        [ 21,  22,  23,  24,  25,  26,  27],
        [ 31,  32,  33,  34,  35,  36,  37],
        [ 41,  42,  43,  44,  45,  46,  47],
        [ 51,  52,  53,  54,  55,  56,  57],
        [ 61,  62,  63,  64,  65,  66,  67],
        [ 71,  72,  73,  74,  75,  76,  77],
        [ 81,  82,  83,  84,  85,  86,  87],
        [ 91,  92,  93,  94,  95,  96,  97],
        [101, 102, 103, 104, 105, 106, 107]])

1.2.2 Вычесть одномерный тензор `b_1d` из двухмерного тензора `a_2d`, так, чтобы каждый элемент одномерного тензора вычитался из всех элементов соответствующих строк двумерного тензора.

_Пример:_

Для входа:
```python
a_2d = torch.tensor([[3,3,3],[4,4,4],[5,5,5]])
b_1d = torch.tensor([1,2,3])
```

Ожидается резульат:

```python
[[2 2 2]
 [2 2 2]
 [2 2 2]]
```

In [14]:
def diff122(a: torch.Tensor, b: torch.Tensor) -> torch.Tensor:
    return a - b.reshape(-1, 1)


a_2d = torch.tensor([[3,3,3],[4,4,4],[5,5,5]])
b_1d = torch.tensor([1,2,3])
diff122(a_2d, b_1d)

tensor([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]])

## 1.3 Индексы, маскирование и прихотливое индексирование

[Документация по функциям для работы с индексами](https://pytorch.org/docs/stable/torch.html#indexing-slicing-joining-mutating-ops)

1.3.1 Получить индексы, для которых элементы тензоров `a` и `b` совпадают.

_Пример:_

Для входа:
```python
a = torch.tensor([1,2,3,2,3,4,3,4,5,6])
b = torch.tensor([7,2,10,2,7,4,9,4,9,8])
```

Ожидается резульат:

```python
tensor([1, 3, 5, 7])
```

In [19]:
a = torch.tensor([1,2,3,2,3,4,3,4,5,6])
b = torch.tensor([7,2,10,2,7,4,9,4,9,8])

c = (a == b) * 1
print(c)
c.topk(c.sum())[1]

tensor([0, 1, 0, 1, 0, 1, 0, 1, 0, 0])


tensor([5, 1, 7, 3])

In [22]:
torch.eq(a, b).argwhere()

tensor([[1],
        [3],
        [5],
        [7]])

1.3.2 Инвертировать порядок элементов в двумерном тензоре `torch.arange(9).view(3,3)`.

Ожидаемый результат:


```python
tensor([[8, 7, 6],
       [5, 4, 3],
       [2, 1, 0]])
```

In [108]:
a = torch.arange(9).view(3,3)
a.flip(-2, 1)

tensor([[8, 7, 6],
        [5, 4, 3],
        [2, 1, 0]])

1.3.3 Из входного тензора a получить только элементы, находящиеся в диапазоне от 5 до 10.

_Пример:_

Для входа:
```python
a = torch.tensor([2, 6, 1, 9, 10, 3, 27])
```

Ожидается результат:

```python
tensor([6, 9, 10])
```

In [109]:
a = torch.tensor([2, 6, 1, 9, 10, 3, 27]) 

a[(5 <= a) & (a <= 10)]

tensor([ 6,  9, 10])

1.3.4 Поменять местами столбец 1 и 2 тензора `torch.arange(9).reshape(3,3)`

In [119]:
a = torch.arange(9).reshape(3,3)
a.index_select(1, torch.tensor([0, 2, 1]))

tensor([[0, 2, 1],
        [3, 5, 4],
        [6, 8, 7]])

1.3.5 Создать тензор 8 на 10 из случайных целых чисел из диапазона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [135]:
rnd = torch.randint(0, 11, (8, 10))
argmin_row = rnd.sum(dim=1).argmin()
print(argmin_row, rnd[argmin_row])

tensor(5) tensor([ 8, 10,  3,  6,  0,  2,  1,  1,  0,  3])


1.3.6 Cоздать тензор из 20 случайных целых чисел от 0 до 100. Обрезать значения тензора (заменить значения, выходящие за диапазон, на крайние значения) снизу по значению 30, сверху по значению 70.

In [150]:
a = torch.randint(0, 100, (20, ))
# _________обрезка снизу________  ___   _______Обрезка сверху_________ #
- a * (a < 30) + (a < 30) * 30 + a + (a > 70) * 70 - a * (a > 70)

tensor([30, 70, 30, 70, 30, 44, 30, 70, 70, 48, 70, 30, 69, 70, 30, 70, 30, 70,
        70, 62])

1.3.7 Создать два тензора размера 30 на 3 из случайных целых чисел из диапазона от 0 до 10 и найти все значения первого тензора, которые больше соответсвующих (по расположению) значений второго тензора. Подсчитать сумму этих значений.

In [152]:
ar1 = torch.randint(0, 10, (30, 3))
ar2 = torch.randint(0, 10, (30, 3))

ar1[ar1 > ar2].sum()

tensor(246)

1.3.8 При помощи прихотливого индексирования для двухмерного массива размерности (20, 20), состоящего из случайных целых чисел в пределах от 0 до 10 получить массив элементов находящихся на диагонали, проходящей над основной диагональю.

In [162]:
ar1 = torch.randint(0, 10, (20, 20))
ar1[range(20), range(20)]

tensor([4, 2, 9, 2, 8, 6, 7, 4, 8, 3, 8, 0, 3, 7, 9, 5, 5, 1, 7, 3])

1.3.9 Задать два двухмерных тензора `ar1` и `ar2` размерности (5, 10), состоящих из случайных целых чисел в пределах от 0 до 10. Удвоить все значения `ar1`, которые совпадают со значениями `ar2`, расположенными на аналогичных позициях.

In [168]:
ar1 = torch.randint(0, 10, (5, 10))
ar2 = torch.randint(0, 10, (5, 10))
print(ar1)
ar1 + ar1 * (ar1 == ar2)

tensor([[2, 1, 6, 0, 5, 6, 3, 4, 8, 4],
        [6, 0, 6, 3, 0, 6, 8, 4, 2, 1],
        [9, 4, 4, 3, 9, 9, 9, 5, 8, 7],
        [8, 3, 2, 7, 8, 0, 7, 7, 3, 7],
        [9, 7, 1, 1, 1, 2, 3, 8, 1, 7]])


tensor([[ 4,  1,  6,  0,  5,  6,  3,  4,  8,  4],
        [ 6,  0, 12,  3,  0,  6,  8,  4,  2,  1],
        [ 9,  8,  4,  3,  9,  9,  9,  5,  8,  7],
        [ 8,  3,  2,  7,  8,  0,  7, 14,  3,  7],
        [ 9,  7,  1,  1,  1,  2,  3,  8,  1,  7]])

1.3.10 Заданы три двухмерных тензора `ar1`, `ar2` и `ar3` размерности (4, 7), состоящие из случайных целых чисел в пределах от 0 до 10. Обнулить все элементы `ar1`, которые больше соответствующих (находящихся в соответствующих позициях) элементов `ar2` и меньше соответствующих элементов `ar3`.

In [169]:
ar1 = torch.randint(0, 10, (4, 7))
ar2 = torch.randint(0, 10, (4, 7))
ar3 = torch.randint(0, 10, (4, 7))

ar1 * (ar1 > ar2) * (ar1 < ar3)

tensor([[0, 5, 0, 0, 0, 0, 0],
        [0, 0, 5, 0, 0, 6, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 4, 0, 0, 0]])

1.3.11 Задан двумерный тензор `ar1` размерности (20, 5), состоящий из случайных целых чисел в пределах от 0 до 20. Определить, в каких столбцах не менее 5 раз встречается значение, максимальное по своей строке.

In [205]:
ar1 = torch.randint(0, 20, (20, 5))

cols, cnts = torch.unique(ar1.max(dim=1)[1], return_counts=True)
cols[cnts >= 5]

tensor([1])

1.3.12 Задан двумерный тензор `ar1` размерности (4, 7), состоящий из случайных  чисел в пределах от 0 до 1. Обнулить все значения в массиве, расположенные строго правее и ниже максимального элемента массива. 

In [67]:
ar1 = torch.rand(4, 7)
bar = (ar1 == ar1.max()) * 1
ar1[bar.max(dim=1)[0].argmax() + 1:, bar.max(dim=0)[0].argmax() + 1:] = 0
ar1

tensor([[0.6773, 0.9909, 0.8663, 0.7612, 0.5749, 0.5140, 0.6529],
        [0.6101, 0.9782, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2292, 0.4844, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3536, 0.0837, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000]])

1.3.13 Построить "one-hot encoding" для одномерного тензора, содержащего целые числа (длина вектора заранее неизвестна, набор значений заранее неизвестен, при этом в итоговой матрице должны присутствовать столбцы для всех натуральных чисел вплоть до максимального встречающегося в исходном массиве).

Пример:

для тензора `torch.tensor([2, 3, 2, 2, 2, 1])`.

Ожидается результат:

```python
tensor([[0., 1., 0.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [1., 0., 0.]])
```

In [221]:
ar = torch.tensor([2, 3, 2, 2, 2, 1])
oh_ar = torch.zeros(ar.shape[0], ar.max() - ar.min() + 1)
oh_ar[range(ar.shape[0]), ar - ar.min()] += 1
oh_ar

tensor([[0., 1., 0.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [1., 0., 0.]])

1.3.14 Создать тензор `arr` из 20 случайных целых чисел от 0 до 100. Найти самое частое значение в тензоре. 
Найти индексы в тензоре, соответствующие самому частому значению. Проверить, как работет алгоритм при двух значениях, имеющих наибольшую встречаемость, предложить приемлемое поведение алгоритма для этого случая. 

In [230]:
arr = torch.randint(0, 101, (20, ))
arr.mode()

torch.return_types.mode(
values=tensor(30),
indices=tensor(15))

In [232]:
torch.mode(torch.tensor([1, 1, 2, 2]))

torch.return_types.mode(
values=tensor(1),
indices=tensor(1))

## 1.4 Математические задачи

1.4.1 Приблизительно (с погрешностью порядка 1%) рассчитать на какой части интервала от 0 до 10 значение функции x * sin(x) больше 0.5.

In [239]:
n = 100
x = torch.linspace(0, 10, n)
(x * torch.sin(x) > 0.5).sum() / n

tensor(0.5200)

1.4.2 Найти все простые числа в пределах ста. (Для решения предлагается использовать Решето Эратосфена) Использовать не более 1 цикла (желательно).

In [347]:
prime_nums = []

for i in range(2, 101):

    if (i % torch.arange(2, i + 1) == 0).sum() == 1:
        prime_nums.append(i)
        
prime_nums

[2,
 3,
 5,
 7,
 11,
 13,
 17,
 19,
 23,
 29,
 31,
 37,
 41,
 43,
 47,
 53,
 59,
 61,
 67,
 71,
 73,
 79,
 83,
 89,
 97]

1.4.3 Найти евклидово расстояние между двумя одномерными тензорами одинаковой размерности, не используя готовые решения из библиотек.

In [249]:
a = torch.tensor([3, 4])
b = torch.tensor([0, 0])

def euclid_dist(a, b = None):
    if b is None:
        b = torch.zeros_like(a)
        
    return ((a - b) ** 2).sum(dim=-1) ** 0.5

euclid_dist(a, b)

tensor(5.)

In [250]:
euclid_dist(a)

tensor(5.)

1.4.4 Создать двумерный тензор 20 на 3, содержащий случайные целые числа от 0 до 100. 
Интерпретируя тензор как 20 векторов из 3х компонент, отсортировать его по длине векторов.

In [253]:
ar = torch.randint(0, 100, (20, 3))
ar[euclid_dist(ar).argsort()]

tensor([[24,  0,  1],
        [31, 29, 17],
        [13, 24, 38],
        [22, 39, 16],
        [40, 25, 51],
        [ 3, 53, 56],
        [15, 18, 75],
        [73, 33,  2],
        [78, 28,  6],
        [45, 68, 22],
        [38, 41, 73],
        [57, 71, 33],
        [89,  0, 47],
        [68, 79,  7],
        [84,  7, 64],
        [58, 50, 76],
        [72, 64, 54],
        [68, 87, 40],
        [51, 48, 96],
        [43, 70, 91]])

1.4.5 Найти "локальные максимумы" в одномерном тензоре (т.е. значения, большие предыдущего и последующего) `torch.tensor([1, 3, 7, 1, 2, 6, 0, 1])` и вывести их индексы.

In [271]:
ar = torch.tensor([1, 3, 7, 1, 2, 6, 0, 1])

cat_ars = torch.zeros(ar.shape[0], 3)
cat_ars[:, 0] += ar
cat_ars[:-1, 1] += ar[1:]
cat_ars[1:, 2] += ar[:-1]
ar[cat_ars.max(dim=1)[1] == 0]

tensor([7, 6, 1])

1.4.6 Задан произвольный массив numpy (например массив из 100 случайных числе от 0 до 1). Необходимо найти в нем число наиболее близкое к заданному.

In [297]:
b = 17
ar = numpy.random.randint(0, 200, 100)
print(ar)
ar[abs(ar - b).argmin()]

[  2 130 191 122  51 165 197 100  84 189 122 149 158 126 131 172  29 120
  42  83  24 148 179  22 152 115 182 105 153  36  19  64 194 148  93  56
  76  49 120  51 144  92  38 132 131   3 131  56  57  71  97  45 142 101
 166 179 129 139 156  68 120 177  47  30  35 149  38 122  74 193  20  56
 148  89 131  66   3  28 180 111 148 136 107  84 184 107  40 107  62  73
 176 169 122 128 173 158 198  56 151 102]


19

1.4.7 Решить матричное уравнение `A*X*B=-C` - найти матрицу X. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [302]:
A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1.]]
B = [[3, -1], [2, 1.]]
C = [[7, 21], [11, 8], [8, 4.]]

A, B, C = torch.tensor(A), torch.tensor(B), torch.tensor(C) 
X = A.inverse() @ (-C) @ B.inverse()

In [304]:
X

tensor([[ 1.0000e+00,  5.9605e-08],
        [-2.0000e+00,  1.0000e+00],
        [ 3.0000e+00, -4.0000e+00]])

In [307]:
-C

tensor([[ -7., -21.],
        [-11.,  -8.],
        [ -8.,  -4.]])

In [305]:
A @ X @ B

tensor([[ -7.0000, -21.0000],
        [-11.0000,  -8.0000],
        [ -8.0000,  -4.0000]])

1.4.8 Проверить, является ли система векторов a1 = (3; −3; 0; 7),
a2 = (2; 2; 4; 7), a3 = (1; 2; 3; 4), a4 = (5; −4; 1; 3) линейно зависимой?

In [332]:
a1 = torch.tensor([3, -3, 0, 7])
a2 = torch.tensor([2, 2, 4, 7])
a3 = torch.tensor([1, 2, 3, 4])
a4 = torch.tensor([5, -4, 1, 3])

a = torch.cat([a1, a2, a3, a4]).reshape(4, 4).double()
a.det()  # зависима, т.к. детерминант равен нулю

tensor(4.0457e-14, dtype=torch.float64)

1.4.9 Сгенирировать тензор из 200 случайных целых чисел, нормально распрделенных cо стандартным отклонением $\sigma = 10$ и матожиданием $\mu = 0$. Построить тензор гистограммы с 20 бинами. 

In [336]:
tensor = torch.randn(200) * 10

tensor.std(), tensor.mean()

(tensor(9.3921), tensor(0.0670))

In [338]:
torch.histogram(tensor, 20)

torch.return_types.histogram(
hist=tensor([ 1.,  0.,  0.,  2.,  4.,  1.,  7.,  9., 27., 24., 14., 26., 27., 19.,
        16.,  9.,  7.,  5.,  0.,  2.]),
bin_edges=tensor([-33.0306, -30.0873, -27.1440, -24.2007, -21.2574, -18.3141, -15.3708,
        -12.4275,  -9.4842,  -6.5409,  -3.5976,  -0.6543,   2.2890,   5.2323,
          8.1756,  11.1189,  14.0623,  17.0056,  19.9489,  22.8922,  25.8355]))